[package]
name = "shouxtech/observers"
description = "Observers to help simplify some specific event handling"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "default.project.json", "wally.toml", "wally.lock"]
exclude = ["**"]

[dependencies]